name: "CI/Code Analysis"

on:
  pull_request:
      types: [opened, synchronize, reopened]
jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@v1.6
      with:
        projectBaseDir: src/
        args: >
          -Dsonar.organization=secdevops
          -Dsonar.projectKey=gihub-devops
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  dependency-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: Marcisbee/dependency-check-action@master
        with:
          PATH: "."

  detect-secrets:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: detect-secrets
        uses: reviewdog/action-detect-secrets@master
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          reporter: github-pr-review